### ISSUE TITLE
Full name attribute returns null

### ISSUE THREAD

**Issue by davidgoate** [getyoti/java#14]
# Unexpected Behaviour For Getting Full Name With Client SDK

In version 1.1 of the Java SDK, the `com.yoti.api.client.HumanProfile#getFullName` method return `null` even though given names and family name attributes contain values.

## Expected Behaviour

I have looked into the default Yoti Client Impl module and  although the JavaDoc says:

```java
/**
     * Equal to ${given_names} + " " + ${family_name}.
     * 
     * @return the given names + the surname
     */
    String getFullName();
```

## Implementation Details

In reality it is actually trying to load another attribute (rather than being a convenience method that appends two String values).

The code does this (`com.yoti.api.client.spi.remote.HumanProfileAdapter#getFullName`)

```java
private static final String ATTRIBUTE_FULL_NAME = "full_name";
 return wrapped.getAttribute(ATTRIBUTE_FULL_NAME);
```

So it would seem that in fact there was no value for that attribute.

## Questions

1. Not sure whether the cause is that the SDK is trying to load the incorrect attribute value or if, in fact, that attribute isn't provided by the backend.
1. Perhaps we should change the JavaDoc to more strongly indicate that it's not a convenience method.
1. If this attribute doesn't exist we should decide to either; deprecate the method, remove the method making it a breaking change for version 1.2 of the Java client SDK or change the implementation to just append the first and last names.

## Edits

@vassyz has also indicated that this attribute value is referenced in the PHP SDK, so we should ensure the decision to move forward is consistent across all SDK implementations so that developers are not confused by inconsistent behaviour.

**Comment by vassyz** [comment]
Will be removed from the only other SDK that has this attribute (PHP). It should be removed from the Java one as well, making sure it doesn't break anything.

**Comment by davidgoate** [comment]
@vassyz I think I understand where you are coming from and that I actually agree with you. However, I'd just like some extra clarity (or at least to make the point) as depending on what is meant by "remove it" from the SDK, it is very easy to say and do. However, "making sure it doesn't break **anything**" is **impossible** given we can have **no idea** who, if any, third parties may be using versions of this SDK that include this method signature.

Given that we already know the method actually doesn't work anyway (i.e. will result in the called getting back null), I'd speculate that it's unlikely anyone is using it and if they are, they either have a bug that they don't yet know about, or they know it's broken and haven't reported it to us **and** have decided to continue using the method anyway.

Sure, we can just delete the method, check everything compiles and that our tests pass and then publish a new version of the SDK to Maven Central. Additionally we could update the release notes/readme with appropriate information on transition and why it was removed. However, if you consider the strict definition of "making sure nothing breaks"  to transcend the "Yoti" ecosystem boundary (which I would suspect most API/SDK designers would) then we must be mindful of the consequences of whatever action we take.

If we literally delete the method, then any third party that is using this method upgrades their code will suddenly not compile - and given what we already know - that usage is probably minimal and the code doesn't actually work there is a chance that this actually doesn't impact anyone at all - the point is we can't be 100% sure of that.

As I see it there are three approaches:

1. Delete the method. Easy, quick. Not backwards compatible.
1. Mark it deprecated and give users (if any) a transition time before actually deleting it.
1. "Fix it" by making it a synthetic convenience method. I.e. since the JavaDoc already states that the result is returning the given names + " " + family names then we could make it do that, rather than using the full name attribute (that doesn't exist).

Personally I'm all for option 1 (full immediate removal). But we must be clear that doing that cannot and is not an outcome in which we can be sure we didn't "break anything".

**Comment by davidgoate** [comment]
Included in https://github.com/getyoti/java/pull/15

If this PR is approved new versions of the libs need to be published to Maven Central.

**Comment by davidgoate** [comment]
@vassyz @qzagarese deleted the method signature and included the changes in https://github.com/getyoti/java/pull/15 ready for review.

**Comment by qzagarese** [comment]
@davidgoate @vassyz the full_name attribute is supported by the backend, however it is not actually used and exposed, so it will probably become deprecated.

As for the way to move forward, I prefer updating the Javadoc, mark the method as deprecated and add a new convenience method like getGivenAndLastNames().

When we actually remove the method, we bump the version to 2.0 as that would be a non backward compatible change.

**Comment by vassyz** [comment]
@davidgoate Sorry for not replying sooner. I can see you already pushed some changes. I agree with @qzagarese 's comment on Java. I'm still undecided on adding the convenience method on the PHP SDK after removing the attribute. Not being a compiled language makes it easier to remove the method without breaking anything that's not already broken.

**Comment by davidgoate** [comment]
@qzagarese @vassyz I reverted my earlier commit (https://github.com/getyoti/java/commit/39074d755f30366b9c2d3eafeb5ff3868258d41d) which removed the method and have implemented as requested in my latest commit (https://github.com/getyoti/java/commit/5cbcc86108f187a0e6864748f02baad1f64969b4).

This is documented and included in the pull request https://github.com/getyoti/java/pull/15

Ready for review.
